"""PAi Legal-owned llama.cpp runtime and installation record."""
from __future__ import annotations

import json
import os
import re
import secrets
import subprocess
import sys
import time
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

from .procutil import hidden

from .hardware import HardwareProfile, app_data_root
from .models import ModelCandidate, download_model, resolve_huggingface_file
from .epistemic import BracketType, wrap_claim
from .netsecurity import bearer_headers, require_loopback_url

SYSTEM_PROMPT = """You are PAi Legal, a private legal case-analysis assistant.
Use only the case record and retrieved sources provided in this request. Never invent a citation, quotation, date, holding, party, docket number, or fact. If the supplied record does not support an answer, say what is missing. Separate record facts, retrieved authorities, analysis, and unresolved items. Every factual statement must name its supplied source marker.

Preserve the supplied Float/Mix/Stir pressure and pattern metadata. Write every atomic claim with exactly one canonical epistemic bracket:
[{claim}] = unverified supplied or working claim
[[claim]] = speculative inference or proposed relation
{[claim]} = known result with a relational explanation
[[[claim]]] = independently corroborated
Never promote a claim because it repeats, has high pressure, or was generated by the model. Never emit [[[validated]]] unless an input source is explicitly locked VALIDATED. This is legal information and work-product assistance, not legal advice."""


class LocalAIError(RuntimeError):
    pass


def installation_path() -> Path:
    return app_data_root() / "config" / "ai_installation.json"


def bundled_runtime() -> Path:
    override = os.environ.get("PAI_LEGAL_LLAMA_SERVER")
    if override:
        return Path(override)
    base = Path(getattr(sys, "_MEIPASS", Path(__file__).resolve().parents[1]))
    name = "llama-server.exe" if os.name == "nt" else "llama-server"
    return base / "resources" / "llama" / name


def read_installation() -> dict:
    path = installation_path()
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}


def save_installation(model: ModelCandidate, model_path: Path, runtime: Path, hardware: HardwareProfile) -> dict:
    payload = {"schema_version": 1, "model_id": model.key, "model_label": model.label, "repo_id": model.repo_id,
               "filename": model.filename, "model_path": str(model_path), "runtime_path": str(runtime),
               "model_revision": model.revision,
               "model_sha256": model.sha256,
               "context": model.context, "gpu_layers": -1 if hardware.vram_gb >= model.size_gb + 2 else 0,
               "hardware": hardware.as_dict(), "installed_at": datetime.now(timezone.utc).isoformat(),
               "launch_confirmed": False}
    path = installation_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(".tmp")
    temporary.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    temporary.replace(path)
    return payload


def provision(model: ModelCandidate, hardware: HardwareProfile, progress=None) -> dict:
    runtime = bundled_runtime()
    if not runtime.is_file():
        raise LocalAIError("The PAi Legal local-AI runtime is missing from this build")
    resolved = resolve_huggingface_file(model)
    model_path = download_model(resolved, app_data_root() / "models", progress)
    return save_installation(resolved, model_path, runtime, hardware)


class PrivateAIClient:
    def __init__(self, resources: dict | None = None, timeout: int = 180):
        self.resources = resources or read_installation()
        self.timeout = timeout
        self.api_url = str(self.resources.get("api_url") or "").rstrip("/")
        self.api_key = str(self.resources.get("api_key") or "")
        self._process: subprocess.Popen | None = None

    @staticmethod
    def _healthy(base: str, api_key: str = "") -> bool:
        for path in ("/health", "/v1/models"):
            try:
                request = urllib.request.Request(
                    base.rstrip("/") + path, headers=bearer_headers(api_key))
                with urllib.request.urlopen(request, timeout=1) as response:
                    if 200 <= response.status < 300:
                        return True
            except Exception:
                pass
        return False

    def start(self) -> None:
        if self.api_url:
            try:
                self.api_url = require_loopback_url(self.api_url, "Private AI")
            except ValueError as exc:
                raise LocalAIError(str(exc)) from exc
            if not self.api_key:
                raise LocalAIError("Private AI endpoint is missing its session authentication token")
            if self._healthy(self.api_url, self.api_key):
                return
        runtime = Path(str(self.resources.get("runtime_path") or bundled_runtime()))
        model = Path(str(self.resources.get("model_path") or ""))
        if not runtime.is_file() or not model.is_file():
            raise LocalAIError("Run Private AI Setup before using analysis")
        port = int(os.environ.get("PAI_LEGAL_AI_PORT", "8081"))
        self.api_url = f"http://127.0.0.1:{port}"
        self.api_key = secrets.token_urlsafe(32)
        args = [str(runtime), "--model", str(model), "--host", "127.0.0.1", "--port", str(port),
                "--api-key", self.api_key, "-c", str(self.resources.get("context") or 8192), "--log-disable"]
        if int(self.resources.get("gpu_layers") or 0):
            args += ["-ngl", str(self.resources["gpu_layers"])]
        self._process = subprocess.Popen(args, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                                         stdin=subprocess.DEVNULL, **hidden())
        deadline = time.time() + self.timeout
        while time.time() < deadline:
            if self._healthy(self.api_url, self.api_key):
                return
            if self._process.poll() is not None:
                raise LocalAIError("The private AI runtime stopped while loading the model")
            time.sleep(0.5)
        self.close()
        raise LocalAIError("The private AI model did not become ready in time")

    def complete(self, question: str, case_context: str = "", authorities: Iterable[dict] = ()) -> str:
        self.start()
        authority_items = tuple(authorities)
        sources = "\n".join(
            f"[PSI:{item.get('source_id', item.get('id', '?'))}] "
            f"BRACKET={item.get('bracket','UNVERIFIED')} "
            f"F/M/S={item.get('float_points',0)}/{item.get('mix_points',0)}/{item.get('stir_points',0)} "
            f"PRESSURE={item.get('total_pressure',0)} COLORS={item.get('float_color','')}/{item.get('mix_color','')}/{item.get('stir_color','')} "
            f"{item.get('title', '')} — {item.get('excerpt', '')}"
            for item in authority_items
        )
        content = f"CASE RECORD\n{case_context or '[No case record supplied]'}\n\nRETRIEVED AUTHORITIES\n{sources or '[No authorities supplied]'}\n\nQUESTION\n{question}"
        body = json.dumps({"model": "local", "messages": [{"role": "system", "content": SYSTEM_PROMPT}, {"role": "user", "content": content}], "temperature": 0.1, "stream": False}).encode()
        headers = {"Content-Type": "application/json", **bearer_headers(self.api_key)}
        request = urllib.request.Request(self.api_url + "/v1/chat/completions", data=body, headers=headers, method="POST")
        try:
            with urllib.request.urlopen(request, timeout=self.timeout) as response:
                payload = json.loads(response.read().decode())
            answer = str(payload["choices"][0]["message"]["content"]).strip()
            validated_claims = _validated_input_claims(case_context, authority_items)
            return enforce_brackets(answer, validated_claims=validated_claims)
        except Exception as exc:
            raise LocalAIError(f"Private analysis failed: {exc}") from exc

    def close(self) -> None:
        if self._process:
            try:
                self._process.terminate(); self._process.wait(timeout=5)
            except Exception:
                try: self._process.kill()
                except Exception: pass
            self._process = None


_SOURCE_MARKER_RE = re.compile(r"\[(?:PSI:)?[^\]]+\]|\[[^\]]+:\d+\]")


def _claim_key(value: str) -> str:
    without_sources = _SOURCE_MARKER_RE.sub(" ", str(value or ""))
    return " ".join(re.findall(r"[a-z0-9]+", without_sources.lower()))


def _validated_input_claims(case_context: str, authorities: Iterable[dict]) -> set[str]:
    allowed: set[str] = set()
    validated_document = False
    for raw in str(case_context or "").splitlines():
        line = raw.strip()
        if line.startswith("=== "):
            validated_document = "| VALIDATED |" in line
            continue
        if validated_document and re.match(r"^\d+:\s+", line):
            key = _claim_key(re.sub(r"^\d+:\s+", "", line))
            if key:
                allowed.add(key)
    for item in authorities:
        if str(item.get("bracket") or "").upper() != "VALIDATED":
            continue
        for field in ("title", "citation", "excerpt"):
            key = _claim_key(str(item.get(field) or ""))
            if key:
                allowed.add(key)
    return allowed


def enforce_brackets(answer: str, *, validated_claims: Iterable[str] = (),
                     allow_validated: bool = False) -> str:
    """Ensure local-model prose cannot escape or self-award the bracket system."""
    allowed = {_claim_key(item) for item in validated_claims if _claim_key(item)}
    output: list[str] = []
    for raw in answer.splitlines():
        line = raw.strip()
        if not line:
            output.append(""); continue
        def validated(match: re.Match) -> str:
            inner = match.group(1)
            # ``allow_validated`` is retained for API compatibility but no
            # longer acts as a request-wide permission. Exact source alignment
            # is required for each claim.
            return match.group(0) if _claim_key(inner) in allowed else f"[[{inner}]]"
        line = re.sub(r"\[\[\[(.*?)\]\]\]", validated, line)
        if line.endswith(":") or line.startswith(("#", "- [{", "- [[", "- {[", "[{", "[[", "{[")):
            output.append(line)
        else:
            output.append(wrap_claim(line, BracketType.SPECULATIVE))
    return "\n".join(output).strip()
